missing 1 required positional argument: 'ttl'
TypeError: __init__() missing 1 required positional argument: 'ttl'
do not know what 'ttl' is but it missing in above codes - please correct